tensorflow:
  modelFetch: SemanticPredictions:0
  model: http://dl.bintray.com/big-data/generic/deeplabv3_mnv2_pascal_train_aug_frozen_inference_graph.pb
  #model: http://dl.bintray.com/big-data/generic/deeplabv3_xception_ade20k_train_2018_05_29_frozen_inference_graph.pb
  #model: http://dl.bintray.com/big-data/generic/deeplabv3_mnv2_cityscapes_train_2018_02_05_frozen_inference_graph.pb
semantic:
  segmentation:
    maskBlendingEnabled: true
    maskTransparency: 0.3
